### ISSUE TITLE
Improve Navigation

### ISSUE THREAD

**Issue by rettinghaus** [trompamusic/mei-friend#2]
By selecting a control element (e.g. dynamics or trills) and navigating to the left/right you'll always end up in the last staff of the system, either on the last layer element of the current or the first layer element of the following measure. 
This is quite confusing and annoying if you have a larger system open. 
At least in cases control elements are positioned by `@startid`, I would expect the referenced element to be the following element. Elements with `@startid` and `@endid` are a bit more tricky I admid.
Anyway it should always stay on the same staff.

**Comment by wergo** [comment]
Thanks for pointing this out. I will look into this.

**Comment by wergo** [comment]
https://github.com/trompamusic/mei-friend/commit/d52010ff3b29e863d34d3db639f20136ffc24373 (MEI-friend 0.2.15) fixes this for control elements that contain `@startid` attributes (always using `@startid` even when `@endid` is there). 

However, for control events with `@tstamp/@staff` attributes, it is still the same behavior at the moment. To be fixed in a future release.
